const PHASER_CONTAINER_DIMENSIONS = {
  WIDTH: 335,
  HEIGHT: 350,
};

const BOARD_DIMENSIONS = {
  WIDTH: 6,
  HEIGHT: 6,
};

const CANVAS_OFFSET = {
  X: 20,
  Y: 320,
};

const COLORS = [0xff0000, 0x971cb5, 0xffff00, 0x00ffff, 0x00ff00];

const CIRCLE_SIZE = 32;

const LINE_WIDTH = 4;

const ANIMATION_DURATION_MS = 350;

const DISTANCE_BETWEEN_DOTS_COEFFICIENT = 1.5;

const DISTANCE_BETWEEN_DOTS =
  BOARD_DIMENSIONS.WIDTH *
  BOARD_DIMENSIONS.HEIGHT *
  DISTANCE_BETWEEN_DOTS_COEFFICIENT;

const SCORE_TEXT_POSITION = {
  X: 7,
  Y: 0,
};

export {
  PHASER_CONTAINER_DIMENSIONS,
  BOARD_DIMENSIONS,
  CANVAS_OFFSET,
  ANIMATION_DURATION_MS,
  COLORS,
  CIRCLE_SIZE,
  LINE_WIDTH,
  DISTANCE_BETWEEN_DOTS,
  SCORE_TEXT_POSITION,
};
